# Generated by Django 5.2.10 on 2026-01-26 09:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Hình ảnh')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Giới thiệu',
                'verbose_name_plural': 'Nội dung giới thiệu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Tin nhắn liên hệ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên chương trình')),
                ('description', tinymce.models.HTMLField(verbose_name='Mô tả')),
                ('date', models.DateTimeField(verbose_name='Ngày giờ biểu diễn')),
                ('price_min', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá vé thấp nhất')),
                ('price_max', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá vé cao nhất')),
                ('icon', models.CharField(default='🎭', max_length=10, verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Hình ảnh')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chương trình',
                'verbose_name_plural': 'Chương trình biểu diễn',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thư viện',
                'verbose_name_plural': 'Thư viện ảnh',
                'ordering': ['-created_at'],
            },
        ),
    ]
