# Generated by Django 5.2.10 on 2026-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Hồ Gươm Opera', max_length=200, verbose_name='Tên website')),
                ('site_title', models.CharField(default='Hồ Gươm Opera - Nhà hát Opera Hà Nội', max_length=200, verbose_name='Tiêu đề website')),
                ('site_description', models.TextField(default='Trải nghiệm nghệ thuật opera đẳng cấp thế giới tại Hà Nội', verbose_name='Mô tả website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('phone', models.CharField(default='0835.661.999', max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(default='contact@hoguomopera.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='40 Hàng Bài, Cửa Nam, Hà Nội', max_length=500, verbose_name='Địa chỉ')),
                ('zalo_phone', models.CharField(default='0835661999', max_length=20, verbose_name='Số Zalo')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Cài đặt website',
                'verbose_name_plural': 'Cài đặt website',
            },
        ),
    ]
