# Generated by Django 5.0.1 on 2026-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics',
            field=models.CharField(blank=True, help_text='VD: G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=100, verbose_name='Google Site Verification'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='keywords',
            field=models.CharField(blank=True, help_text='Các từ khóa cách nhau bởi dấu phẩy', max_length=500, verbose_name='Từ khóa SEO'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200x630px', null=True, upload_to='site/', verbose_name='Ảnh chia sẻ mạng xã hội'),
        ),
    ]
